image: java:8-jdk

stages:
  - build
  - test
# - deploy

before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew clean
    - ./gradlew build -x test -x integrationTest
  artifacts:
    paths:
      - build/*.war
    expire_in: 1 week

unit-test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew jacocoFullReport
    - cat build/reports/jacoco/jacocoFullReport/html/index.html
  artifacts:
    paths:
      - build/reports/jacoco/jacocoFullReport
    expire_in: 1 week

integration-test:
  stage: test
  script:
    - ./gradlew integrationTest
  only:
    - tags


#deploy:
#  stage: deploy
#  script:
#    - ./gradlew cargoRedeployRemote
#  only:
#    - tags